# speficy your container name, such as deepcluster/tensorflow:1.12-python3.6 or deepcluster/pytorch:1.0-python3.7
container_image: deepcluster/pytorch:1.0-python3.7

# provide known dataset name or local datasets
dataset_name: cifar10
dataset_path:

# number of GPU used to train, default it 1
worker_required: 1

# command to run
# use the environment variable $DATASET to access dataset
# and write output to $OUTPUT
command: python main.py -d $DATASET -o $OUTPUT

# you can also define your config here
# config.yaml will be placed next to main.py
# so you can access your config from code from "./config.yaml"
